import dotenv from "dotenv";

/* CONFIGURE ENV VARIABLES */
dotenv.config();

const APP_PORT = process.env.APP_PORT || 4000;
const MONGO_DB_URI = process.env.MONGO_DB_URI;
const DEBUG_MODE = process.env.DEBUG_MODE;
const BASE_URL = process.env.BASE_URL;
/* FOR EMAIL */
const SMTP_HOST = process.env.SMTP_HOST;
const SMTP_PORT = process.env.SMTP_PORT;
const MAIL_USER = process.env.MAIL_USER;
const MAIL_PASSWORD = process.env.MAIL_PASSWORD;
const ADMIN_MAIL = process.env.ADMIN_MAIL;

const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
const FORGET_PASSWORD_TOKEN_SECRET = process.env.FORGET_PASSWORD_TOKEN_SECRET;

/* RULES FOR LIBRARY */

/* ISSUED BOOKS ALLOW */
const NUMBER_OF_BOOKS_ALLOWED_TO_STUDENT = 3;
const NUMBER_OF_BOOKS_ALLOWED_TO_TEACHER = 5;
const NUMBER_OF_BOOKS_ALLOWED_TO_HOD = 8;

const NUMBER_OF_DAYS_OF_STUDENT = 7;
const NUMBER_OF_DAYS_OF_TEACHER_OR_HOD = 15;

/* RESERVED BOOKS ALLOW */
const NUMBER_OF_RESERVED_BOOKS_ALLOW_TO_STUDENT = 2;
const NUMBER_OF_RESERVED_BOOKS_ALLOW_TO_TEACHER = 5;
const NUMBER_OF_RESERVED_BOOKS_ALLOW_TO_HOD = 10;
const MAX_RESERVATION_DURATION = 2;

export {
  APP_PORT,
  MONGO_DB_URI,
  DEBUG_MODE,
  SMTP_HOST,
  SMTP_PORT,
  MAIL_USER,
  MAIL_PASSWORD,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  FORGET_PASSWORD_TOKEN_SECRET,
  BASE_URL,
  NUMBER_OF_BOOKS_ALLOWED_TO_STUDENT,
  NUMBER_OF_BOOKS_ALLOWED_TO_TEACHER,
  NUMBER_OF_BOOKS_ALLOWED_TO_HOD,
  NUMBER_OF_RESERVED_BOOKS_ALLOW_TO_HOD,
  NUMBER_OF_RESERVED_BOOKS_ALLOW_TO_TEACHER,
  NUMBER_OF_RESERVED_BOOKS_ALLOW_TO_STUDENT,
  MAX_RESERVATION_DURATION,
  NUMBER_OF_DAYS_OF_STUDENT,
  NUMBER_OF_DAYS_OF_TEACHER_OR_HOD,
  ADMIN_MAIL,
};
